---
name: ci
on:
  pull_request:
  push:
    branches:
      - 'release/**'
jobs:
  yamllint:
    uses: networkservicemesh/.github/.github/workflows/yamllint.yaml@main

  shellcheck:
    uses: networkservicemesh/.github/.github/workflows/shellcheck.yaml@main

  restrict-nsm-deps:
    uses: networkservicemesh/.github/.github/workflows/restrict-nsm-deps.yaml@main
    with:
      allowed_repositories: "api, sdk"

  checkgomod:
    uses: networkservicemesh/.github/.github/workflows/checkgomod.yaml@main

  exclude-replace:
    uses: networkservicemesh/.github/.github/workflows/exclude-replace.yaml@main
